yatube/about/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'about'

urlpatterns = [
    path('author/', TemplateView.as_view(template_name="about/author.html"),
         name='author'),
    path('tech/', TemplateView.as_view(template_name="about/tech.html"),
         name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('group/<slug:slug>/', views.group_list, name='group_list'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<footer class='border-top text-center py-3'>
  <p>© {% now 'Y' %} Copyright <span style='color:red'>Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
<header>
  {% load static %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {% with request.resolver_match.view_name as view_name %} 
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link 
            {% if view_name  == 'about:author' %}
              active
            {% endif %}"
            href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link 
            {% if view_name  == 'about:tech' %}
              active
            {% endif %}"
            href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.username %}
        <li class="nav-item"> 
          <a class="nav-link 
            {% if view_name  == 'posts:post_create' %}
              active
            {% endif %}"
            href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link"
            href="{% url 'posts:index' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link"
            href="{% url 'posts:index' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light
            {% if view_name  == 'users:login' %}
              active
            {% endif %}"
            href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light
            {% if view_name  == 'users:signup' %}
              active
            {% endif %}"
            href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
      {% endwith %}
    </div>
  </nav>      
</header>

yatube/templates/includes/post_card.html
{% load thumbnail %}
<article>
  <li>
    Имя автора: <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
  {% if not group and post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}
    <hr>
  {% endif %}
<article>