yatube/about/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'about'

urlpatterns = [
    path('author/', TemplateView.as_view(template_name="about/author.html"),
         name='author'),
    path('tech/', TemplateView.as_view(template_name="about/tech.html"),
         name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('group/<slug:slug>/', views.group_list, name='group_list'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(
        unique=True,
        max_length=200
    )
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(CreatedModel):
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ('-pub_date',)


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        null=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
        verbose_name='Автор записей',
    )

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')
        labels = {
            'text': 'текст',
            'group': 'группа',
            'image': 'картинка'
        }
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
            'image': 'Выберите картинку'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария',
        }
        help_texts = {
            'text': 'Текст нового комментария',
        }

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def paginate_queryset(queryset, request):
    paginator = Paginator(queryset, settings.COUNT_POST)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


@cache_page(20)
def index(request):
    posts = Post.objects.select_related('group', 'author')
    context = {
        'page_obj': paginate_queryset(posts, request)
    }
    return render(request, 'posts/index.html', context)


def group_list(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author')
    context = {
        'group': group,
        'page_obj': paginate_queryset(posts, request)
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=author)
    posts_count = posts.count()
    following = request.user.is_authenticated and Follow.objects.filter(
        author=author, user=request.user
    ).exists()
    context = {
        'author': author,
        'page_obj': paginate_queryset(posts, request),
        'posts_count': posts_count,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comment_form = CommentForm(request.POST or None)
    comment_post = post.comments.all()
    context = {
        'post': post,
        'form': comment_form,
        'comments': comment_post
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    context = {
        'title': 'Добавить запись',
        'form': form
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.select_related('author', 'group').filter(
        author__following__user=request.user
    )
    context = {
        'title': 'Все посты ваших подписок',
        'page_obj': paginate_queryset(posts, request)
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(
            author=author,
            user=request.user
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(
        user=request.user,
        author__username=username
    ).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if form.instance.pk %}
  Редактировать пост
{% else %}
  Новый пост
{% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
      <div class="card-header">       
        {% if form.instance.pk %}
          Редактировать пост
        {% else %}
          Новый пост
        {% endif %}            
      </div>
      <div class="card-body">        
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              {{ field }}
              <div>
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
          </div>
        </form>
      </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% cache 20 page_index %}
  {% block title %}
    {{ title }}
  {% endblock %}
  {% block content %}
    <div class="container py-5">
      <h3>Посты избранных авторов </h3> 
      {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
        <article>
          {% include 'includes/post_card.html' %}
          {% if post.group %}   
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% else %}
            <a href="{% url 'posts:index' %}">группы нет {{ posts.group.title }}</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        </article>
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}  
    </div>
  {% endblock %}
{% endcache %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества: {{ group.title }}
{% endblock %}
{% block content %}
  <h3>{{ group.title }}</h3>
  <p>{{ group.description }}</p>
    {% for post in posts %}
      {% include 'includes/post_card.html' %}
    {% endfor %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% cache 20 index_page %}
  {% block title %}
    Последние обновления на сайте
  {% endblock %}
  {% load thumbnail %}
  {% block content %}
    {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
        {% include 'includes/post_card.html' %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  {% endblock %}
{% endcache %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}
  {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }} 
        <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
  </article>
  <article>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    <li class="list-group-item">
      Группа:
      {% if post.group %}
        <p>{{ post.group }}</p>
      {% endif %}
      {% if not group and post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
    </li>
    <li>
      Имя автор: {{ post.author.get_full_name }}
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      Всего постов автора: {{ user.posts.all.count }}
    </li>
    <li class="list-group-item">
      <br><a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    </li>
    <p>{{ post.text }}</p>
    {% if post.author == request.user %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">редактировать запись</a> 
    {% endif %}
    {% if user.is_authenticated %}
    <div class="card my-4">
      <h5 class="card-header">Добавить комментарий:</h5>
      <div class="card-body">
        <form method="post" action="{% url 'posts:add_comment' post.id %}">
          {% csrf_token %}      
          <div class="form-group mb-2">
            {{ form.text|addclass:"form-control" }}
          </div>
          <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
      </div>
    </div>
    {% endif %}
    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">{{ comment.author.username }}</a>
          </h5>
            <p>{{ comment.text }}</p>
        </div>
      </div>
    {% endfor %} 
    {% if not forloop.last %}
      <hr>
    {% endif %}
  <article>
{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
    Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% load thumbnail %}
{% block content %}
  <div class="mb-5">
    <h3>Все посты пользователя {{ author.get_full_name }}</h3>
    <h3>Всего постов: {{posts_count}} </h3>
    {% if request.user != author %}
      {% if following %}
        <a class="btn btn-lg btn-light"href="{% url 'posts:profile_unfollow' author.username %}" role="button">Отписаться</a>
      {% else %}
        <a class="btn btn-lg btn-primary"href="{% url 'posts:profile_follow' author.username %}" role="button">Подписаться</a>
      {% endif %}
    {% endif %}
    {% for post in page_obj %}
      {% include 'includes/post_card.html' %}
    {% endfor %}
      {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}